[tool.poetry]
name = "sceneify.core"
version = "0.1.0"
description = ""
authors = ["Brendan Allan <brendonovich@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.8"
simpleobsws = "^1.3.1"
asyncio = "^3.4.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-asyncio = "^0.17.2"
black = {version = "^21.12b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"